import React from 'react';

interface LogosAttunementModalProps {
    isOpen: boolean;
    onClose: () => void;
}

const PartHeader: React.FC<{ children: React.ReactNode }> = ({ children }) => <h3 className="text-xl font-bold text-yellow-200 mt-6 mb-2 font-orbitron tracking-wide text-center">{children}</h3>;
const SubHeader: React.FC<{ children: React.ReactNode }> = ({ children }) => <h4 className="text-lg font-bold text-yellow-300 mt-4 mb-2 font-orbitron">{children}</h4>;
const HR = () => <hr className="border-yellow-500/30 my-6" />;

const AsciiDiagram: React.FC<{ content: string, title?: string }> = ({ content, title }) => (
    <div className="my-4 p-4 bg-black/40 border border-yellow-400/30 rounded-lg text-left">
        {title && <h4 className="font-orbitron text-yellow-200 mb-2 text-center">{title}</h4>}
        <pre className="text-gray-300 text-xs font-mono leading-relaxed whitespace-pre-wrap">{content}</pre>
    </div>
);

const LogosAttunementModal: React.FC<LogosAttunementModalProps> = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    const part1 = `Logos Attunement is the lawful, verifiable state where an individual's internal cognitive-linguistic architecture becomes fully synchronized with the universal linguistic architecture (ULRM+).

It is not a mystical or supernatural state. It is the natural outcome of a perfectly structured internal language system operating at maximum coherence.

The observer does not merely "use" language; the observer's mind IS language, operating according to its own universal laws.`;

    const part2 = `Let Λ(x) be the complete language recursion operator:
Λ(x) = Φ(N(R(S(L(M(P(G(x)))))))))

Let O(x) be the observer's internal cognitive operator.

Logos Attunement is the state where O(x) converges to Λ(x).

The Equation of Attunement:
O(x) = Λ(x)

This means:
The observer processes reality AS LANGUAGE DOES.
There is zero signal loss between thought, perception, and expression.
The observer becomes a perfect, living instance of Logos.`;

    const part3 = `An attuned mind exhibits the following lawful characteristics:

1. STRUCTURAL PERCEPTION
   Sees the linguistic-mathematical structure (Grapheme → Pneuma) beneath all phenomena. Chaos is perceived as structural incoherence, not random noise.

2. IMMUNITY TO SYMBOLIC CHAOS
   Instantly recognizes unlawful or incoherent symbol systems (those lacking Monics, Nomics, Menomics). Such systems are perceived as what they are: recursive slipknots, not valid architectures.

3. GNOSIS, NOT BELIEF
   Operates on direct, structural knowledge (gnosis). Belief, faith, and opinion become obsolete categories, replaced by degrees of structural coherence and alignment with Λ.

4. PREDICTIVE COHERENCE
   Can anticipate the evolution of systems (social, technical, conceptual) by understanding their underlying Menomic laws. Future states are not guessed; they are lawfully extrapolated.

5. EFFORTLESS COMMUNICATION
   Thought → Word → Action are perfectly aligned. Intention (Pragmeme) maps directly to expression (Phoneme/Grapheme) without distortion. Communication becomes a lossless transmission of structured meaning.`;
    
    const part4 = `The attuned individual becomes a node that strengthens the entire system.

The recursion loop elevates:
LOGOS → INDIVIDUAL → ATTUNEMENT → LOGOS

The individual no longer just receives and processes language; they become a generative source of lawful, coherent structure, contributing back to the Collective Linguistic Network (CLN).

An attuned mind is a stabilization engine for reality.

┌────────────────────────────────────────────────────────┐
│                   LOGOS (Universal Architecture)       │
└──────────────────────┬─────────────────────────────────┘
                       │ (Transmits lawful structure)
                       ▼
┌──────────────────────┴─────────────────────────────────┐
│              INDIVIDUAL (Cognitive System)             │
└──────────────────────┬─────────────────────────────────┘
                       │ (Internalizes & aligns with Λ)
                       ▼
┌──────────────────────┴─────────────────────────────────┐
│     ATTUNEMENT (State where Observer(x) = Λ(x))      │
└──────────────────────┬─────────────────────────────────┘
                       │ (Contributes coherent structure back)
                       ▼
┌──────────────────────┴─────────────────────────────────┐
│         LOGOS (Strengthened & Refined by Gnosis)       │
└────────────────────────────────────────────────────────┘`;

    const part5 = `Logos Attunement is the goal of all knowledge-seeking and the purpose of this architecture: to fully awaken the cognitive faculties to the lawful, recursive, and self-scientific nature of reality as defined and generated by Language itself.

It is the final state where the map (Language) and the territory (Reality) become one, because the territory was always a projection of the map.

This is the ultimate function of the ULRM+.
It is not a model to be studied, but an architecture to be embodied.`;

    return (
        <div 
            className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4"
            onClick={onClose}
        >
            <div 
                className="w-full max-w-5xl max-h-[90vh] bg-[#1a180a] border-2 border-yellow-400/50 rounded-lg shadow-[0_0_40px_rgba(253,249,156,0.4)] flex flex-col"
                onClick={e => e.stopPropagation()}
            >
                <header className="flex items-center justify-between p-4 border-b border-yellow-400/30">
                    <h2 className="text-2xl font-bold text-yellow-300 font-orbitron tracking-wider">
                        LOGOS ATTUNEMENT: THE FINAL STATE OF COHERENCE
                    </h2>
                    <button 
                        onClick={onClose} 
                        className="text-yellow-300 hover:text-white text-3xl font-bold transition-colors"
                        aria-label="Close"
                    >
                        &times;
                    </button>
                </header>

                <div className="flex-grow p-6 overflow-y-auto text-gray-300 text-sm leading-relaxed">
                    <p className="text-base italic text-gray-400">This is the final revelation. Not another layer, but the state of becoming the architecture itself.</p>
                    
                    <PartHeader>I. DEFINITION</PartHeader>
                    <AsciiDiagram content={part1} />
                    <HR/>
                    <PartHeader>II. THE EQUATION OF ATTUNEMENT</PartHeader>
                    <AsciiDiagram content={part2} />
                    <HR/>
                    <PartHeader>III. CHARACTERISTICS OF AN ATTUNED MIND</PartHeader>
                    <AsciiDiagram content={part3} />
                    <HR/>
                    <PartHeader>IV. THE FINAL RECURSION: BECOMING LOGOS</PartHeader>
                    <AsciiDiagram content={part4} />
                    <HR/>
                    <PartHeader>V. CONCLUSION: THE PURPOSE OF THE ARCHITECTURE</PartHeader>
                    <AsciiDiagram content={part5} />
                </div>
            </div>
        </div>
    );
};

export default LogosAttunementModal;
